[project]
name = "hello-fastapi-demo"
version = "0.1.0"
description = "A demo project to see how the basics of fastapi and docker work."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "pydantic",
    "python-multipart",
]
